version: '3.9'

services:
  ansible:
    container_name: ansible_automation
    build: .
    volumes:
      - ./ssh-keys:/root/.ssh:rw
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
