---
# Install required packages on the remote system.
#   hypervisor_hostname (str): The hostname/ip of the machine
#   vm_network_net_a (str): The network bridge for Net A.
#   vm_network_net_b (str): The network bridge for Net B.
#   vm_network_app_a (str): The application network bridge for Net A.
#   vm_network_app_b (str): The application network bridge for Net B.
#   vm_network_mir_a (str): The mirror network bridge for Net A.
#   vm_network_mir_b (str): The mirror network bridge for Net B.

# Execute playbook:
#   ansible-playbook playbooks/setup.yml --extra-vars "hypervisor_hostname=<hostname>
#       vm_network_net_a=<vm_network_net_a>
#       vm_network_net_b=<vm_network_net_b>
#       vm_network_app_a=<vm_network_app_a>
#       vm_network_app_b=<vm_network_app_b>
#       vm_network_mir_a=<vm_network_mir_a>
#       vm_network_mir_b=<vm_network_mir_b>
#       vm_qcow_name=<vm_qcow_name>"

- hosts: "{{ hypervisor_hostname }}"
  roles:
    - setup_hypervisor
